try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(c){window.Popup=function(g,b){var a=this;a.positionType=b||"fixed";a.el=c("<div />",{id:g}).css({position:this.positionType}).appendTo("body");a.IS_VISIBLE=!1;a.setContent=function(b){typeof b!=="undefined"&&a.el.html(b);return a};a.show=function(b){typeof b!=="undefined"&&a.setContent(b);a.IS_VISIBLE=!0;a.position();a.el.show();return a};a.hide=function(){if(a.IS_VISIBLE)a.el.hide(),a.IS_VISIBLE=!1;return a};a.position=function(b,c){return a.positionType==="fixed"?a.positionFixed():a.positionAbsolute(b,
c)};a.onClick=function(b){b.stopPropagation()};a.positionFixed=function(){if(a.IS_VISIBLE){var b=Math.floor((c(window).width()-a.el.outerWidth())/2),e=Math.floor((c(window).height()-a.el.outerHeight())/2);a.el.css({left:b<0?0:b,top:e<0?0:e})}return a};a.positionAbsolute=function(b,c){a.el.css({left:b,top:c});return a};a.positionType==="fixed"&&c(window).resize(a.positionFixed);a.el.click(a.onClick);return a}})(jQuery);
(function(c){var g=function(b){var a=this,d={contID:"rotator",sliderClass:"slides",slideClass:"slide",controlsClass:"controls",nextText:">>",prevText:"<<",z:1,transitionTime:1E3,hoverControls:!1,gidAtt:"gid",timeoutTime:7500,showControls:!1,linkTo:!1,useSlideTextInControls:!1,linkClickCallback:function(){},autoRotate:!1,appendControlsTo:!1},e;for(e in b)d[e]=b[e]||d[e];for(e in d)a[e]=d[e];a.container=null;a.slider=null;a.slides=null;a.controls=null;a.sliderTimeout=null;a.currentSlide=[];a.nextSlide=
null;a.binaryControls=null;a.RUNNING=!1;a.other=!1;a.init=function(){if(c("#"+a.contID).length)a.container=c("#"+a.contID),a.slider=a.container.find("."+a.sliderClass),a.slides=a.slider.find("."+a.slideClass),a.controls=a.makeControls(),a.controls.children().first().addClass("active"),a.slides.last().addClass("active"),a.currentSlide=a.slides.last().fadeTo(a.transitionTime,1),a.slides.not(".active").fadeOut(0),c(window).resize(a.onResize),a.onResize(),a.RUNNING=!0;return a};a.isRunning=function(){return a.RUNNING};
a.onResize=function(){if(a.container.is(":visible")){if(!a.sliderTimeout&&a.autoRotate)a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)}else if(a.sliderTimeout&&a.autoRotate)clearTimeout(a.sliderTimeout),a.sliderTimeout=null};a.makeControls=function(){var b=c("<div />").addClass(a.controlsClass+" norm");a.slides.each(function(){var e=c(this).attr(a.gidAtt),e=c("<div />",{}).attr(a.gidAtt,e).click(a.ctrlClickHandle).prependTo(b);a.hoverControls&&e.mouseover(a.ctrlClickHandle);a.useSlideTextInControls&&
e.append('<span class="line"></span><span>'+c(this).html()+"</span>");if(c(this).attr("thumb")){var o=JSON.parse(c(this).attr("thumb"));c("<span />").css({"background-image":'url("'+o[0]+'")'}).appendTo(e)}});a.showControls||b.hide();if(a.showControls==="binary")a.binaryControls=a.makeBinaryControls();a.appendControlsTo&&c(a.appendControlsTo).length?b.appendTo(a.appendControlsTo):b.appendTo(a.container);return b};a.makeBinaryControls=function(){var b=c("<div />").addClass(a.controlsClass+" bin");
c("<span />",{text:a.prevText}).addClass("prev").click(a.binaryCtrlClickHandle).appendTo(b);c("<span />",{text:a.nextText}).addClass("next").click(a.binaryCtrlClickHandle).appendTo(b);b.appendTo(a.appendControlsTo);b.appendTo(a.container);return b};a.ctrlClickHandle=function(){var b=c(this).attr(a.gidAtt);a.slideChange(b);return a.linkClickCallback(b,a.linkTo)};a.binaryCtrlClickHandle=function(){var b=c(this).hasClass("prev")?a.getPreviousSlide().attr(a.gidAtt):a.getNextSlide().attr(a.gidAtt);a.slideChange(b);
return a.linkClickCallback(b,a.linkTo)};a.getNextSlide=function(){return a.currentSlide.next().length?a.currentSlide.next():a.currentSlide.parent().children().first()};a.getPreviousSlide=function(){return a.currentSlide.prev().length?a.currentSlide.prev():a.currentSlide.parent().children().last()};a.slideChange=function(b){var c=a.getControlByID(b);if(!c.hasClass("active"))return a.sliderTimeout&&clearTimeout(a.sliderTimeout),a.z++,a.nextSlide=a.getSlideByID(b),a.fadeChange(),a.controls.find(".active").removeClass("active"),
c.addClass("active"),a.autoRotate?a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime):!0};a.fadeChange=function(){if(!a.nextSlide)return!1;a.slider.find(a.currentSlide).stop(!1,!1);a.slides.not(a.nextSlide).stop(!0,!1);a.nextSlide.addClass("active").css({zIndex:a.z}).stop(!0,!0).fadeTo(a.transitionTime,1);a.slides.not(a.nextSlide).stop(!0,!0).fadeOut(a.transitionTime).removeClass("active");a.currentSlide=a.nextSlide;a.nextSlide=null};a.getControlByID=function(b){return!b?!1:a.controls.find("["+
a.gidAtt+'="'+b+'"]')};a.getSlideByID=function(b){return!b?!1:a.slider.find("["+a.gidAtt+'="'+b+'"]')};a.sliderTimeoutFunc=function(){return a.slideChange(a.getNextSlide().attr(a.gidAtt))};return a.init()};window.EaseRotator=g;window.EaseRotatorController=function(b){var a=this,d={rotatorsConfig:[],timeoutTime:7500},e;for(e in b)d[e]=b[e]||d[e];for(e in d)a[e]=d[e];a.rotators={};a.sliderTimeout=null;a.init=function(){if(typeof a.rotatorsConfig==="object"&&a.rotatorsConfig.length)c.each(a.rotatorsConfig,
a.startRotator),a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime);return a};a.startRotator=function(){if(this.linkTo)this.linkClickCallback=a.linkClickCallback;a.rotators[this.contID]=new g(this)};a.sliderTimeoutFunc=function(){clearTimeout(a.sliderTimeout);c.each(a.rotators,a.rotateInstance);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)};a.rotateInstance=function(){!this.autoRotate&&this.RUNNING&&this.container.is(":visible")&&this.slideChange(this.getNextSlide().attr(this.gidAtt));
return!0};a.linkClickCallback=function(b,c){if(!b||!c)return!1;clearTimeout(a.sliderTimeout);var e=a.rotators[c];typeof e==="object"&&e.isRunning()&&e.slideChange(b);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)};return a.init()}})(jQuery);
(function(c){window.EasePhotoGallery=function(g){var b=this,a={galleryContSelector:"ease-photo-gallery",linkCls:"ease-img-link",showTitles:!1,showDescriptions:!1,useFrame:!1,dataAttr:"ease_full",dataEl:!1,paginate:!1,paginateContCls:"gallery-page-controls",popupId:"easePopup",isStatic:!1},d;for(d in g)a[d]=g[d]||a[d];for(d in a)b[d]=a[d];b.currentI=0;b.allData=[];b.fullData=[];b.currentPage=1;b.maxPages=0;b.pageContainer=!1;b.pageControls=!1;b.isIE=Ease.ie||c("html.ie").length?!0:!1;b.galleryExists=
!1;b.popup=!1;b.frameCont=null;b.frame=null;b.images={};b.init=function(){if(c(b.galleryContSelector).length){b.galleryExists=!0;b.gallery=c(b.galleryContSelector);if(b.paginate&&b.dataEl)return b.initPaginated();b.links=b.gallery.find("."+b.linkCls);b.links.each(function(a){var f=c(this).attr(b.dataAttr);b.allData[a]=c.parseJSON(f)});b.links.click(b.linkClick);c("body").click(b.closePop)}};b.initPaginated=function(){var a=JSON.parse(c(b.dataEl).text());c.each(a,function(){b.fullData.push(this);b.allData.push(this.full)});
b.maxPages=Math.ceil(a.length/b.paginate);b.useFrame&&b.makeFrame();b.maxPages>1&&(b.makePageContainer(),b.makePaginateControls());c.fn.disableSelection&&c(".pageNext, .pagePrev").disableSelection();b.isStatic?(b.currentI=0,b.makePopup()):(b.buildPage(),c("body").click(b.closePop))};b.makeFrame=function(){var a=b.fullData[0];b.frameCont=c("<div />",{id:"gallery-frame"});b.frame=c("<img />",{src:a.full.src,thisI:0,alt:a.full.title}).attr(b.dataAttr,JSON.stringify(a.full)).click(b.loadPhoto).appendTo(b.frameCont);
b.frameTip=c("<div />",{html:"Click to expand"}).addClass("frame-tip").appendTo(b.frameCont);return b.frameCont.insertBefore(b.gallery)};b.frameClick=function(){};b.makePageContainer=function(){b.pageContainer=c("<div />",{id:"gallery-page-container"});return b.pageContainer.prependTo(b.gallery)};b.buildPage=function(){var a=b.currentPage*b.paginate-b.paginate,c=b.currentPage*b.paginate-1;for(b.pageContainer.html("");a<=c;a++)a<b.fullData.length&&b.makeThumbLink(a).appendTo(b.pageContainer);b.pageControls.find(".pageCounter").text(""+
b.currentPage+" of "+b.maxPages)};b.makeThumbLink=function(a){var f=b.fullData[a];return c("<a>",{href:f.full.src,thisI:a,title:f.full.title,html:c("<img />",{src:f.thumb[0],width:f.thumb[1],height:f.thumb[2]})}).attr(b.dataAttr,JSON.stringify(f.full)).addClass(b.linkCls).click(b.linkClick)};b.makePaginateControls=function(){var a={nextBttn:c("<div />",{html:"Next Page"}).addClass("pageNext").click(b.nextPage),prevBttn:c("<div />",{html:"Prev Page"}).addClass("pagePrev").click(b.prevPage),counter:c("<div />").addClass("pageCounter"),
clear:c("<div />").addClass("clearfix")};b.pageControls=c("<div />",{}).addClass(b.paginateContCls);for(var f in a)b.pageControls.append(a[f]);return b.pageControls.insertAfter(b.pageContainer)};b.nextPage=function(){b.currentPage<b.maxPages?b.currentPage++:b.currentPage=1;b.buildPage()};b.prevPage=function(){b.currentPage>1?b.currentPage--:b.currentPage=b.maxPages;b.buildPage()};b.linkClick=function(a){a.stopPropagation();a.preventDefault();return b.useFrame?b.loadPhotoInFrame.call(this,a):b.loadPhoto.call(this,
a)};b.loadPhotoInFrame=function(a){a.stopPropagation();a.preventDefault();a=c(this).attr("thisI");b.frame.attr({thisI:c(this).attr("thisI"),src:b.fullData[a].full.src}).attr(b.dataAttr,JSON.stringify(b.fullData[a].full))};b.loadPhoto=function(a){a.stopPropagation();a.preventDefault();b.currentI=c(this).attr("thisI")?c(this).attr("thisI"):c(this).index();b.makePopup()};b.closePop=function(){b.popup&&b.popup.hide()};b.nextPop=function(){b.currentI++;if(b.currentI>=b.allData.length)b.currentI=0;b.switchPop()};
b.prevPop=function(){b.currentI==0?b.currentI=b.allData.length-1:b.currentI--;b.switchPop()};b.positionPop=function(){var a=b.popup.width();b.popup.height();dW=c(window).width();sT=c(document).scrollTop();left=Math.floor((dW-a)/2);left<0&&(left=0);b.popup.css({top:40+sT,left:left}).show()};b.resizeHeight=function(b,a,c){b=Math.round(c*a/b);return{height:c,width:b}};b.resizeWidth=function(b,a,c){return{height:Math.round(c*b/a),width:c}};b.switchPop=function(){b.popup.children(".line, img, #pInfo, #pDesc, #pTitle").remove();
var a=b.allData[b.currentI],f=a.height,h=a.width,o="high";b.isStatic&&h>f&&(o="wide");if(!b.isStatic&&h>k)var k=c(window).width()-40,h=b.resizeWidth(f,h,k),f=h.height,h=h.width;if(!b.isStatic&&f>d)var d=c(window).height()-80,h=b.resizeHeight(f,h,d),f=h.height,h=h.width;f={line:c("<div />").addClass("line"),img:c("<img />",{src:a.src,height:f,width:h}).addClass(o).click(b.nextPop)};if(b.showTitles||b.showDescriptions)f.info=c("<div />",{id:"pInfo"});b.showTitles&&c("<div />",{id:"pTitle",html:a.title}).appendTo(f.info);
b.showDescriptions&&c("<div />",{id:"pDesc",html:a.desc}).appendTo(f.info);for(var l in f)b.popup.append(f[l]);b.isStatic?b.popup.show():b.positionPop();b.preloadAdjacentImages()};b.preloadAdjacentImages=function(){b.currentI+1>=b.fullData.length?b.preloadImage(0):b.preloadImage(b.currentI+1);b.currentI-1<0?b.preloadImage(b.fullData.length-1):b.preloadImage(b.currentI-1)};b.preloadImage=function(a){if(!b.images[a])b.images[a]=new Image,b.images[a].src=b.allData[a].src};b.makePopup=function(){if(!b.popup){var a=
{nextBttn:c("<div />",{id:"pNext",html:"next"}).click(b.nextPop),prevBttn:c("<div />",{id:"pPrev",html:"prev"}).click(b.prevPop)};if(!b.isStatic)a.closeBttn=c("<div />",{id:"pClose",html:"&times;"}).click(b.closePop);b.popup=c("<div />",{id:b.popupId}).click(function(a){a.stopPropagation()});for(var d in a)b.popup.append(a[d]);b.isStatic?b.popup.prependTo(b.gallery):b.popup.prependTo("body")}b.switchPop()};b.init();c(window).resize(function(){b.popup&&!b.popup.is(":hidden")&&b.switchPop()});return b.galleryExists?
b:!1}})(jQuery);
(function(c){window.EasePopup=function(g){if(!g||!g.length)return!1;var b=this;b.$self=g;b.init=function(){b.$self.appendTo("body");b.$self.click(function(a){a.stopPropagation()})};b.show=function(){b.position();b.$self.show(0)};b.hide=function(){b.$self.hide(0)};b.position=function(){var a=b.$self.outerWidth(),d=b.$self.outerHeight(),a=Math.floor((c(window).width()-a)/2);a<0&&(a=0);d=Math.floor((c(window).height()-d)/2+c(window).scrollTop());d<0&&(d=0);b.$self.css({top:d,left:a})};b.init()}})(jQuery);(function(c){function g(){if(c("#mc-embedded-subscribe-form").length>0){var a=c("#mc-embedded-subscribe-form"),b=a.find("input"),k=a.find("button"),d=!1;a.submit(function(l){l.preventDefault();var l=b.val(),e=Ease.TemplateUrl+"/mailchimp_subscribe.php",f=function(b,d){if(typeof b==="undefined"||!b)b="Well, something went wrong.";var e;c("<span />",{text:b}).addClass(!d?"mcError error":"mcError success").insertAfter(k);return setTimeout(function(){var b=a.find(".mcError");b.length&&b.fadeOut(900,function(){c(this).remove()})},
2500)};a.find(".mcError").remove();if(l==="")return f("We need an email address, please."),!1;d||(d=!0,c.get(e,"email="+l,function(a){d=!1;a=JSON.parse(a);if(a.error){var b=a.error;switch(!0){case a.error.indexOf("already subscribed")!==-1:b="That email's already on our list!";break;case a.error.indexOf("Invalid Email Address")!==-1:b="We need a proper email address, please."}return f(b)}return f("You have been signed up!",!0)}))})}}function b(){if(c("#carousel").length){var a=c("#carousel"),b=c("#outer"),
d=a.find("#inner"),e=a.find(".nav"),a=a.find("a"),l=d.find(".active"),f=0;b.outerWidth();var g=a.first().outerWidth(),j=parseInt(d.css("left").replace("px",""),10),m=!0,q=j;c.each(a,function(){f+=c(this).outerWidth()});e.click(function(){var a=c(this).hasClass("back")?1:-1;parseInt(b.css("left").replace("px",""),10);j+=g*a;j>q||j<5*g-f?a=j-=g*a:(a=m?0:250,a=d.stop(!1,!1).animate({left:j},a,r));return a});var r=function(){m&&p()},p=function(){if(l.position().left-5*g+j>=0)return e.last().trigger("click");
else m=!1};p()}}function a(){if(c("#communityPage").length){var a=c("li.forum a"),b=new Popup("forumPopup"),d=c("<div />",{"data-href":"litmotors.com","data-num-posts":10,"data-width":720}).addClass("fb-comments"),e=function(){typeof window.FB!=="undefined"&&typeof window.FB.XFBML!=="undefined"?FB.XFBML.parse(document.getElementById("forumPopup")):setTimeout(e,15)};a.click(function(a){a.preventDefault();a.stopPropagation();b.show(d);e()});c("body").click(function(){b.hide()})}}function d(){if(c("#shirtForm").length){var a=
c("li.t-shirt a"),b=c("#shirtForm"),d=new Popup("shirtPopup"),e=new Popup("reservePopup"),f=b.find("#theSize"),g=b.find("#theColor");d.setContent(b);a.click(function(a){a.preventDefault();a.stopPropagation();e.hide();d.show()});var n=function(a){a.stopPropagation()},j=function(){var a=c("<div />",{id:"step2"}).click(n);c.each(["google","paypal"],function(){c("<div />",{id:this}).click(m).appendTo(a)});c("<h2 />",{html:"To complete your purchase please choose your preferred payment gateway by clicking on desired icon below:"}).prependTo(a);
return a},m=function(a){var b=c(this).attr("id");a.stopPropagation();e.show("<h2>In a moment you will be transferred to "+b+" to complete your reservation.</h2>");(b=="paypal"?c("#paypalForm"):c("#googleForm")).submit()};b.find("button").click(function(a){a.preventDefault();a.stopPropagation();d.hide();e.show(j())});b.click(n);c("body").click(function(){d.hide();e.hide()});b.find("select").change(function(){var a=f.val(),b=g.val();c('[name="os0"]').val(b);c('[name="os1"]').val(f.val());c('[name="item_selection_1"]').val({Black:{S:1,
M:2,L:3,XL:4,XXL:5},Grey:{S:6,M:7,L:8,XL:9,XXL:10},Orange:{S:11,M:12,L:13,XL:14,XXL:15}}[b][a])})}}function e(){if(c("#reserveForm").length){var a=c("#reserveForm"),b=[],d=new Popup("reservePopup");token=0;valid=!0;if(c("#faq").length){var e=c("#faq").find("a"),f=new Popup("tooltip","absolute");e.click(function(a){a.preventDefault();a.stopPropagation();typeof d!=="undefined"&&d.hide();a=c(this).parent().children(".tip");if(a.length){f.setContent(a.html());var b=c(this).offset(),a=b.top-Math.floor(f.el.outerHeight()/
4),b=b.left-f.el.outerWidth()-20;f.position(b,a).show()}_gaq.push(["_trackEvent","Reserve",Ease.pageName,"FAQ Click",c(this).text()])});c("body").click(function(){f.hide()})}var g=function(){var a="";c.each(b,function(){a+="<div>"+this+"</div>"});d.setContent(a).show()},n=function(a){a.parent().addClass("error");return valid=!1},j=function(){b=[];var d=a.serializeArray();_gaq.push(["_trackEvent","Reserve",Ease.pageName,"Form Submitted",d[0].value]);c.ajax({url:Ease.TemplateUrl+"/reserve.php",data:d,
type:"post",complete:function(){},success:m,error:function(){}})},m=function(c){if(typeof c.status=="undefined")return b.push("An error occurred please try again later."),g();if(c.status!="ok")return typeof c.focus!="undefined"&&n(a.find('[name="'+c.focus+'"]')),b.push(c.message),g();if(c.proceed)token=c.token,d.show(q());else if(c.message=="promotional_deposit")return d.show("Thank you for your reservation!")},q=function(){var a=c("<div />",{id:"step2"});c.each(["google","paypal"],function(){c("<div />",
{id:this}).click(r).appendTo(a)});c("<h2 />",{html:"To complete your reservation please choose your preferred payment gateway by clicking on desired icon below:"}).prependTo(a);return a},r=function(){var a=c(this).attr("id");d.show("<h2>In a moment you will be transferred to "+a+" to complete your reservation.</h2>");_gaq.push(["_trackEvent","Reserve",Ease.pageName,"Gateway Selected",a]);c.ajax({url:Ease.TemplateUrl+"/reserve.php",type:"post",data:{base_url:Ease.Url,template_url:Ease.TemplateUrl,
current_url:window.location.href.toString().replace(window.location.search,""),token:token,gateway:a},success:p,error:function(a){d.show("Error:<br/>"+a.responseText)}})},p=function(b){if(typeof b.status=="undefined")return d.show("An error occurred please try again later.");if(b.status!="ok")return d.show(b.message);if(b.proceed&&b.link&&b.method&&b.link)b.method=="get"?window.location.href=b.link:(a.attr({action:b.link}),a.submit())};c("body").click(function(){d.hide()});c(window).resize(function(){d.position()});
a.find('[type="submit"]').click(function(c){c.preventDefault();c.stopPropagation();typeof f!=="undefined"&&f.hide();var c=null,d={deposit:"Please choose your deposit amount.",country:"Please choose your country."},e={zip:"Zip Code is required",firstname:"First Name is required",lastname:"Last Name is required",address:"Address is required",city:"City is required",state:"State is required",email:"A valid Email is required",phone:"A Phone Number is Required"};a.find(".error").removeClass("error");b=
[];valid=!0;for(var k in d)if(c=a.find("[name="+k+"]"),!c.val()||c.val()=="null")n(c),b.push(d[k]);for(k in e)if(c=a.find("[name="+k+"]"),!c.val()||c.val().length<2)n(c),b.push(e[k]);return valid?j():g()});c("#actionReturn").length&&d.show(c("#actionReturn").html())}}function f(){if(c("#dentistRotate").length){new EaseRotator({contID:"dentistRotate",gidAtt:"gid",sliderClass:"slides",transitionTime:750,timeoutTime:3E3,showControls:!0,autoRotate:!0,appendControlsTo:"#dControls"});var a=new EasePopup(c("#litTechVideo")),
b=new EasePopup(c("#fortuneVideo")),d=new EasePopup(c("#c1Story")),e=[a,b,d];c(".links-wrap .tech").click(function(b){b.preventDefault();b.stopPropagation();a.show()});c(".links-wrap .fortune").click(function(a){a.preventDefault();a.stopPropagation();b.show()});c(".links-wrap .story").click(function(a){a.preventDefault();a.stopPropagation();d.show()});c("body").click(function(){c.each(e,function(){this.hide()})});c(window).resize(function(){c.each(e,function(){this.position()})})}}c(document).ready(function(){console.log("hello common ready");
c("html.ie").length?Ease.ie=!0:Ease.ie=!1;c("html.lte8").length?Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;c("#homeRotate").length&&new EaseRotator({contID:"homeRotate",transitionTime:1E3,timeoutTime:7500,showControls:"binary",autoRotate:!0,appendControlsTo:"#controlWrap"});f();c("#rotatingGallery").length&&new EasePhotoGallery({galleryContSelector:"#rotatingGallery",dataEl:"#galleryJson",paginate:1E3,isStatic:!0,showTitles:!0,showDescriptions:!0});e();
b();d();a();g()})})(jQuery);
