try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(c){window.Popup=function(g,a){var b=this;b.positionType=a||"fixed";b.el=c("<div />",{id:g}).css({position:this.positionType}).appendTo("body");b.IS_VISIBLE=!1;b.setContent=function(a){typeof a!=="undefined"&&b.el.html(a);return b};b.show=function(a){typeof a!=="undefined"&&b.setContent(a);b.IS_VISIBLE=!0;b.position();b.el.show();return b};b.hide=function(){if(b.IS_VISIBLE)b.el.hide(),b.IS_VISIBLE=!1;return b};b.position=function(a,c){return b.positionType==="fixed"?b.positionFixed():b.positionAbsolute(a,
c)};b.onClick=function(a){a.stopPropagation()};b.positionFixed=function(){if(b.IS_VISIBLE){var a=Math.floor((c(window).width()-b.el.outerWidth())/2),e=Math.floor((c(window).height()-b.el.outerHeight())/2);b.el.css({left:a<0?0:a,top:e<0?0:e})}return b};b.positionAbsolute=function(a,c){b.el.css({left:a,top:c});return b};b.positionType==="fixed"&&c(window).resize(b.positionFixed);b.el.click(b.onClick);return b}})(jQuery);
(function(c){var g=function(a){var b=this,d={contID:"rotator",sliderClass:"slides",slideClass:"slide",controlsClass:"controls",nextText:">>",prevText:"<<",z:1,transitionTime:1E3,hoverControls:!1,gidAtt:"gid",timeoutTime:7500,showControls:!1,linkTo:!1,useSlideTextInControls:!1,linkClickCallback:function(){},autoRotate:!1,appendControlsTo:!1},e;for(e in a)d[e]=a[e]||d[e];for(e in d)b[e]=d[e];b.container=null;b.slider=null;b.slides=null;b.controls=null;b.sliderTimeout=null;b.currentSlide=[];b.nextSlide=
null;b.binaryControls=null;b.RUNNING=!1;b.other=!1;b.init=function(){if(c("#"+b.contID).length)b.container=c("#"+b.contID),b.slider=b.container.find("."+b.sliderClass),b.slides=b.slider.find("."+b.slideClass),b.controls=b.makeControls(),b.controls.children().first().addClass("active"),b.slides.last().addClass("active"),b.currentSlide=b.slides.last().fadeTo(b.transitionTime,1),b.slides.not(".active").fadeOut(0),c(window).resize(b.onResize),b.onResize(),b.RUNNING=!0;return b};b.isRunning=function(){return b.RUNNING};
b.onResize=function(){if(b.container.is(":visible")){if(!b.sliderTimeout&&b.autoRotate)b.sliderTimeout=setTimeout(b.sliderTimeoutFunc,b.timeoutTime)}else if(b.sliderTimeout&&b.autoRotate)clearTimeout(b.sliderTimeout),b.sliderTimeout=null};b.makeControls=function(){var a=c("<div />").addClass(b.controlsClass+" norm");b.slides.each(function(){var e=c(this).attr(b.gidAtt),e=c("<div />",{}).attr(b.gidAtt,e).click(b.ctrlClickHandle).prependTo(a);b.hoverControls&&e.mouseover(b.ctrlClickHandle);b.useSlideTextInControls&&
e.append('<span class="line"></span><span>'+c(this).html()+"</span>");if(c(this).attr("thumb")){var o=JSON.parse(c(this).attr("thumb"));c("<span />").css({"background-image":'url("'+o[0]+'")'}).appendTo(e)}});b.showControls||a.hide();if(b.showControls==="binary")b.binaryControls=b.makeBinaryControls();b.appendControlsTo&&c(b.appendControlsTo).length?a.appendTo(b.appendControlsTo):a.appendTo(b.container);return a};b.makeBinaryControls=function(){var a=c("<div />").addClass(b.controlsClass+" bin");
c("<span />",{text:b.prevText}).addClass("prev").click(b.binaryCtrlClickHandle).appendTo(a);c("<span />",{text:b.nextText}).addClass("next").click(b.binaryCtrlClickHandle).appendTo(a);a.appendTo(b.appendControlsTo);a.appendTo(b.container);return a};b.ctrlClickHandle=function(){var a=c(this).attr(b.gidAtt);b.slideChange(a);return b.linkClickCallback(a,b.linkTo)};b.binaryCtrlClickHandle=function(){var a=c(this).hasClass("prev")?b.getPreviousSlide().attr(b.gidAtt):b.getNextSlide().attr(b.gidAtt);b.slideChange(a);
return b.linkClickCallback(a,b.linkTo)};b.getNextSlide=function(){return b.currentSlide.next().length?b.currentSlide.next():b.currentSlide.parent().children().first()};b.getPreviousSlide=function(){return b.currentSlide.prev().length?b.currentSlide.prev():b.currentSlide.parent().children().last()};b.slideChange=function(a){var c=b.getControlByID(a);if(!c.hasClass("active"))return b.sliderTimeout&&clearTimeout(b.sliderTimeout),b.z++,b.nextSlide=b.getSlideByID(a),b.fadeChange(),b.controls.find(".active").removeClass("active"),
c.addClass("active"),b.autoRotate?b.sliderTimeout=setTimeout(b.sliderTimeoutFunc,b.timeoutTime):!0};b.fadeChange=function(){if(!b.nextSlide)return!1;b.slider.find(b.currentSlide).stop(!1,!1);b.slides.not(b.nextSlide).stop(!0,!1);b.nextSlide.addClass("active").css({zIndex:b.z}).stop(!0,!0).fadeTo(b.transitionTime,1);b.slides.not(b.nextSlide).stop(!0,!0).fadeOut(b.transitionTime).removeClass("active");b.currentSlide=b.nextSlide;b.nextSlide=null};b.getControlByID=function(a){return!a?!1:b.controls.find("["+
b.gidAtt+'="'+a+'"]')};b.getSlideByID=function(a){return!a?!1:b.slider.find("["+b.gidAtt+'="'+a+'"]')};b.sliderTimeoutFunc=function(){return b.slideChange(b.getNextSlide().attr(b.gidAtt))};return b.init()};window.EaseRotator=g;window.EaseRotatorController=function(a){var b=this,d={rotatorsConfig:[],timeoutTime:7500},e;for(e in a)d[e]=a[e]||d[e];for(e in d)b[e]=d[e];b.rotators={};b.sliderTimeout=null;b.init=function(){if(typeof b.rotatorsConfig==="object"&&b.rotatorsConfig.length)c.each(b.rotatorsConfig,
b.startRotator),b.sliderTimeout=setTimeout(b.sliderTimeoutFunc,b.timeoutTime);return b};b.startRotator=function(){if(this.linkTo)this.linkClickCallback=b.linkClickCallback;b.rotators[this.contID]=new g(this)};b.sliderTimeoutFunc=function(){clearTimeout(b.sliderTimeout);c.each(b.rotators,b.rotateInstance);return b.sliderTimeout=setTimeout(b.sliderTimeoutFunc,b.timeoutTime)};b.rotateInstance=function(){!this.autoRotate&&this.RUNNING&&this.container.is(":visible")&&this.slideChange(this.getNextSlide().attr(this.gidAtt));
return!0};b.linkClickCallback=function(a,c){if(!a||!c)return!1;clearTimeout(b.sliderTimeout);var e=b.rotators[c];typeof e==="object"&&e.isRunning()&&e.slideChange(a);return b.sliderTimeout=setTimeout(b.sliderTimeoutFunc,b.timeoutTime)};return b.init()}})(jQuery);
(function(c){window.EasePhotoGallery=function(g){var a=this,b={galleryContSelector:"ease-photo-gallery",linkCls:"ease-img-link",showTitles:!1,showDescriptions:!1,useFrame:!1,dataAttr:"ease_full",dataEl:!1,paginate:!1,paginateContCls:"gallery-page-controls",popupId:"easePopup",isStatic:!1},d;for(d in g)b[d]=g[d]||b[d];for(d in b)a[d]=b[d];a.currentI=0;a.allData=[];a.fullData=[];a.currentPage=1;a.maxPages=0;a.pageContainer=!1;a.pageControls=!1;a.isIE=Ease.ie||c("html.ie").length?!0:!1;a.galleryExists=
!1;a.popup=!1;a.frameCont=null;a.frame=null;a.images={};a.init=function(){if(c(a.galleryContSelector).length){a.galleryExists=!0;a.gallery=c(a.galleryContSelector);if(a.paginate&&a.dataEl)return a.initPaginated();a.links=a.gallery.find("."+a.linkCls);a.links.each(function(b){var f=c(this).attr(a.dataAttr);a.allData[b]=c.parseJSON(f)});a.links.click(a.linkClick);c("body").click(a.closePop)}};a.initPaginated=function(){var b=JSON.parse(c(a.dataEl).text());c.each(b,function(){a.fullData.push(this);a.allData.push(this.full)});
a.maxPages=Math.ceil(b.length/a.paginate);a.useFrame&&a.makeFrame();a.maxPages>1&&(a.makePageContainer(),a.makePaginateControls());c.fn.disableSelection&&c(".pageNext, .pagePrev").disableSelection();a.isStatic?(a.currentI=0,a.makePopup()):(a.buildPage(),c("body").click(a.closePop))};a.makeFrame=function(){var b=a.fullData[0];a.frameCont=c("<div />",{id:"gallery-frame"});a.frame=c("<img />",{src:b.full.src,thisI:0,alt:b.full.title}).attr(a.dataAttr,JSON.stringify(b.full)).click(a.loadPhoto).appendTo(a.frameCont);
a.frameTip=c("<div />",{html:"Click to expand"}).addClass("frame-tip").appendTo(a.frameCont);return a.frameCont.insertBefore(a.gallery)};a.frameClick=function(){};a.makePageContainer=function(){a.pageContainer=c("<div />",{id:"gallery-page-container"});return a.pageContainer.prependTo(a.gallery)};a.buildPage=function(){var b=a.currentPage*a.paginate-a.paginate,c=a.currentPage*a.paginate-1;for(a.pageContainer.html("");b<=c;b++)b<a.fullData.length&&a.makeThumbLink(b).appendTo(a.pageContainer);a.pageControls.find(".pageCounter").text(""+
a.currentPage+" of "+a.maxPages)};a.makeThumbLink=function(b){var f=a.fullData[b];return c("<a>",{href:f.full.src,thisI:b,title:f.full.title,html:c("<img />",{src:f.thumb[0],width:f.thumb[1],height:f.thumb[2]})}).attr(a.dataAttr,JSON.stringify(f.full)).addClass(a.linkCls).click(a.linkClick)};a.makePaginateControls=function(){var b={nextBttn:c("<div />",{html:"Next Page"}).addClass("pageNext").click(a.nextPage),prevBttn:c("<div />",{html:"Prev Page"}).addClass("pagePrev").click(a.prevPage),counter:c("<div />").addClass("pageCounter"),
clear:c("<div />").addClass("clearfix")};a.pageControls=c("<div />",{}).addClass(a.paginateContCls);for(var f in b)a.pageControls.append(b[f]);return a.pageControls.insertAfter(a.pageContainer)};a.nextPage=function(){a.currentPage<a.maxPages?a.currentPage++:a.currentPage=1;a.buildPage()};a.prevPage=function(){a.currentPage>1?a.currentPage--:a.currentPage=a.maxPages;a.buildPage()};a.linkClick=function(b){b.stopPropagation();b.preventDefault();return a.useFrame?a.loadPhotoInFrame.call(this,b):a.loadPhoto.call(this,
b)};a.loadPhotoInFrame=function(b){b.stopPropagation();b.preventDefault();b=c(this).attr("thisI");a.frame.attr({thisI:c(this).attr("thisI"),src:a.fullData[b].full.src}).attr(a.dataAttr,JSON.stringify(a.fullData[b].full))};a.loadPhoto=function(b){b.stopPropagation();b.preventDefault();a.currentI=c(this).attr("thisI")?c(this).attr("thisI"):c(this).index();a.makePopup()};a.closePop=function(){a.popup&&a.popup.hide()};a.nextPop=function(){a.currentI++;if(a.currentI>=a.allData.length)a.currentI=0;a.switchPop()};
a.prevPop=function(){a.currentI==0?a.currentI=a.allData.length-1:a.currentI--;a.switchPop()};a.positionPop=function(){var b=a.popup.width();a.popup.height();dW=c(window).width();sT=c(document).scrollTop();left=Math.floor((dW-b)/2);left<0&&(left=0);a.popup.css({top:40+sT,left:left}).show()};a.resizeHeight=function(a,b,c){a=Math.round(c*b/a);return{height:c,width:a}};a.resizeWidth=function(a,b,c){return{height:Math.round(c*a/b),width:c}};a.switchPop=function(){a.popup.children(".line, img, #pInfo, #pDesc, #pTitle").remove();
var b=a.allData[a.currentI],f=b.height,h=b.width,o="high";a.isStatic&&h>f&&(o="wide");if(!a.isStatic&&h>k)var k=c(window).width()-40,h=a.resizeWidth(f,h,k),f=h.height,h=h.width;if(!a.isStatic&&f>d)var d=c(window).height()-80,h=a.resizeHeight(f,h,d),f=h.height,h=h.width;f={line:c("<div />").addClass("line"),img:c("<img />",{src:b.src,height:f,width:h}).addClass(o).click(a.nextPop)};if(a.showTitles||a.showDescriptions)f.info=c("<div />",{id:"pInfo"});a.showTitles&&c("<div />",{id:"pTitle",html:b.title}).appendTo(f.info);
a.showDescriptions&&c("<div />",{id:"pDesc",html:b.desc}).appendTo(f.info);for(var l in f)a.popup.append(f[l]);a.isStatic?a.popup.show():a.positionPop();a.preloadAdjacentImages()};a.preloadAdjacentImages=function(){a.currentI+1>=a.fullData.length?a.preloadImage(0):a.preloadImage(a.currentI+1);a.currentI-1<0?a.preloadImage(a.fullData.length-1):a.preloadImage(a.currentI-1)};a.preloadImage=function(b){if(!a.images[b])a.images[b]=new Image,a.images[b].src=a.allData[b].src};a.makePopup=function(){if(!a.popup){var b=
{nextBttn:c("<div />",{id:"pNext",html:"next"}).click(a.nextPop),prevBttn:c("<div />",{id:"pPrev",html:"prev"}).click(a.prevPop)};if(!a.isStatic)b.closeBttn=c("<div />",{id:"pClose",html:"&times;"}).click(a.closePop);a.popup=c("<div />",{id:a.popupId}).click(function(a){a.stopPropagation()});for(var d in b)a.popup.append(b[d]);a.isStatic?a.popup.prependTo(a.gallery):a.popup.prependTo("body")}a.switchPop()};a.init();c(window).resize(function(){a.popup&&!a.popup.is(":hidden")&&a.switchPop()});return a.galleryExists?
a:!1}})(jQuery);
(function(c){window.EasePopup=function(g){if(!g||!g.length)return!1;var a=this;a.$self=g;a.id=g.children().attr("id");a.path="/"+g.attr("data-path");a.init=function(){a.$self.appendTo("body");jwplayer(a.id).setup({height:480,width:864,image:Ease.TemplateUrl+a.path+".jpg",modes:[{type:"html5"},{type:"flash",src:Ease.TemplateUrl+"/js/player.swf"},{type:"download"}],levels:[{file:Ease.TemplateUrl+a.path+".mp4"},{file:Ease.TemplateUrl+a.path+".webm"},{file:Ease.TemplateUrl+a.path+".ogg"}]});a.$self.click(function(a){a.stopPropagation()})};
a.show=function(){a.position();a.$self.css({zIndex:1E5});jwplayer(a.id).play()};a.hide=function(){a.$self.css({left:"-9999em",zIndex:0});jwplayer(a.id).stop()};a.position=function(){var b=a.$self.outerWidth(),d=a.$self.outerHeight(),b=Math.floor((c(window).width()-b)/2);b<0&&(b=0);d=Math.floor((c(window).height()-d)/2+c(window).scrollTop());d<0&&(d=0);a.$self.css({top:d,left:b})};a.init()}})(jQuery);(function(c){function g(){if(c("#mc-embedded-subscribe-form").length>0){var a=c("#mc-embedded-subscribe-form"),b=a.find("input"),k=a.find("button"),d=!1;a.submit(function(l){l.preventDefault();var l=b.val(),e=Ease.TemplateUrl+"/mailchimp_subscribe.php",f=function(b,d){if(typeof b==="undefined"||!b)b="Well, something went wrong.";var e;c("<span />",{text:b}).addClass(!d?"mcError error":"mcError success").insertAfter(k);return setTimeout(function(){var b=a.find(".mcError");b.length&&b.fadeOut(900,function(){c(this).remove()})},
2500)};a.find(".mcError").remove();if(l==="")return f("We need an email address, please."),!1;d||(d=!0,c.get(e,"email="+l,function(a){d=!1;a=JSON.parse(a);if(a.error){var b=a.error;switch(!0){case a.error.indexOf("already subscribed")!==-1:b="That email's already on our list!";break;case a.error.indexOf("Invalid Email Address")!==-1:b="We need a proper email address, please."}return f(b)}return f("You have been signed up!",!0)}))})}}function a(){if(c("#carousel").length){var a=c("#carousel"),b=c("#outer"),
d=a.find("#inner"),e=a.find(".nav"),a=a.find("a"),l=d.find(".active"),f=0;b.outerWidth();var g=a.first().outerWidth(),j=parseInt(d.css("left").replace("px",""),10),m=!0,q=j;c.each(a,function(){f+=c(this).outerWidth()});e.click(function(){var a=c(this).hasClass("back")?1:-1;parseInt(b.css("left").replace("px",""),10);j+=g*a;j>q||j<5*g-f?a=j-=g*a:(a=m?0:250,a=d.stop(!1,!1).animate({left:j},a,r));return a});var r=function(){m&&p()},p=function(){if(l.position().left-5*g+j>=0)return e.last().trigger("click");
else m=!1};p()}}function b(){if(c("#communityPage").length){var a=c("li.forum a"),b=new Popup("forumPopup"),d=c("<div />",{"data-href":"litmotors.com","data-num-posts":10,"data-width":720}).addClass("fb-comments"),e=function(){typeof window.FB!=="undefined"&&typeof window.FB.XFBML!=="undefined"?FB.XFBML.parse(document.getElementById("forumPopup")):setTimeout(e,15)};a.click(function(a){a.preventDefault();a.stopPropagation();b.show(d);e()});c("body").click(function(){b.hide()})}}function d(){if(c("#shirtForm").length){var a=
c("li.t-shirt a"),b=c("#shirtForm"),d=new Popup("shirtPopup"),e=new Popup("reservePopup"),f=b.find("#theSize"),g=b.find("#theColor");d.setContent(b);a.click(function(a){a.preventDefault();a.stopPropagation();e.hide();d.show()});var n=function(a){a.stopPropagation()},j=function(){var a=c("<div />",{id:"step2"}).click(n);c.each(["google","paypal"],function(){c("<div />",{id:this}).click(m).appendTo(a)});c("<h2 />",{html:"To complete your purchase please choose your preferred payment gateway by clicking on desired icon below:"}).prependTo(a);
return a},m=function(a){var b=c(this).attr("id");a.stopPropagation();e.show("<h2>In a moment you will be transferred to "+b+" to complete your reservation.</h2>");(b=="paypal"?c("#paypalForm"):c("#googleForm")).submit()};b.find("button").click(function(a){a.preventDefault();a.stopPropagation();d.hide();e.show(j())});b.click(n);c("body").click(function(){d.hide();e.hide()});b.find("select").change(function(){var a=f.val(),b=g.val();c('[name="os0"]').val(b);c('[name="os1"]').val(f.val());c('[name="item_selection_1"]').val({Black:{S:1,
M:2,L:3,XL:4,XXL:5},Grey:{S:6,M:7,L:8,XL:9,XXL:10},Orange:{S:11,M:12,L:13,XL:14,XXL:15}}[b][a])})}}function e(){if(c("#reserveForm").length){var a=c("#reserveForm"),b=[],d=new Popup("reservePopup");token=0;valid=!0;if(c("#faq").length){var e=c("#faq").find("a"),f=new Popup("tooltip","absolute");e.click(function(a){a.preventDefault();a.stopPropagation();typeof d!=="undefined"&&d.hide();a=c(this).parent().children(".tip");if(a.length){f.setContent(a.html());var b=c(this).offset(),a=b.top-Math.floor(f.el.outerHeight()/
4),b=b.left-f.el.outerWidth()-20;f.position(b,a).show()}_gaq.push(["_trackEvent","Reserve",Ease.pageName,"FAQ Click",c(this).text()])});c("body").click(function(){f.hide()})}var g=function(){var a="";c.each(b,function(){a+="<div>"+this+"</div>"});d.setContent(a).show()},n=function(a){a.parent().addClass("error");return valid=!1},j=function(){b=[];var d=a.serializeArray();_gaq.push(["_trackEvent","Reserve",Ease.pageName,"Form Submitted",d[0].value]);c.ajax({url:Ease.TemplateUrl+"/reserve.php",data:d,
type:"post",complete:function(){},success:m,error:function(){}})},m=function(c){if(typeof c.status=="undefined")return b.push("An error occurred please try again later."),g();if(c.status!="ok")return typeof c.focus!="undefined"&&n(a.find('[name="'+c.focus+'"]')),b.push(c.message),g();if(c.proceed)token=c.token,d.show(q());else if(c.message=="promotional_deposit")return d.show("Thank you for your reservation!")},q=function(){var a=c("<div />",{id:"step2"});c.each(["google","paypal"],function(){c("<div />",
{id:this}).click(r).appendTo(a)});c("<h2 />",{html:"To complete your reservation please choose your preferred payment gateway by clicking on desired icon below:"}).prependTo(a);return a},r=function(){var a=c(this).attr("id");d.show("<h2>In a moment you will be transferred to "+a+" to complete your reservation.</h2>");_gaq.push(["_trackEvent","Reserve",Ease.pageName,"Gateway Selected",a]);c.ajax({url:Ease.TemplateUrl+"/reserve.php",type:"post",data:{base_url:Ease.Url,template_url:Ease.TemplateUrl,
current_url:window.location.href.toString().replace(window.location.search,""),token:token,gateway:a},success:p,error:function(a){d.show("Error:<br/>"+a.responseText)}})},p=function(b){if(typeof b.status=="undefined")return d.show("An error occurred please try again later.");if(b.status!="ok")return d.show(b.message);if(b.proceed&&b.link&&b.method&&b.link)b.method=="get"?window.location.href=b.link:(a.attr({action:b.link}),a.submit())};c("body").click(function(){d.hide()});c(window).resize(function(){d.position()});
a.find('[type="submit"]').click(function(c){c.preventDefault();c.stopPropagation();typeof f!=="undefined"&&f.hide();var c=null,d={deposit:"Please choose your deposit amount.",country:"Please choose your country."},e={zip:"Zip Code is required",firstname:"First Name is required",lastname:"Last Name is required",address:"Address is required",city:"City is required",state:"State is required",email:"A valid Email is required",phone:"A Phone Number is Required"};a.find(".error").removeClass("error");b=
[];valid=!0;for(var k in d)if(c=a.find("[name="+k+"]"),!c.val()||c.val()=="null")n(c),b.push(d[k]);for(k in e)if(c=a.find("[name="+k+"]"),!c.val()||c.val().length<2)n(c),b.push(e[k]);return valid?j():g()});c("#actionReturn").length&&d.show(c("#actionReturn").html())}}function f(){if(c("#dentistRotate").length){new EaseRotator({contID:"dentistRotate",gidAtt:"gid",sliderClass:"slides",transitionTime:750,timeoutTime:3E3,showControls:!0,autoRotate:!0,appendControlsTo:"#dControls"});var a=new EasePopup(c("#litTechVideo")),
b=new EasePopup(c("#fortuneVideo")),d=new EasePopup(c("#c1Story")),e=[a,b,d];c(".links-wrap .tech").click(function(b){b.preventDefault();b.stopPropagation();a.show()});c(".links-wrap .fortune").click(function(a){a.preventDefault();a.stopPropagation();b.show()});c(".links-wrap .story").click(function(a){a.preventDefault();a.stopPropagation();d.show()});c("body").click(function(){c.each(e,function(){this.hide()})});c(window).resize(function(){c.each(e,function(){this.position()})})}}c(document).ready(function(){console.log("hello common ready");
c("html.ie").length?Ease.ie=!0:Ease.ie=!1;c("html.lte8").length?Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;c("#homeRotate").length&&new EaseRotator({contID:"homeRotate",transitionTime:1E3,timeoutTime:7500,showControls:"binary",autoRotate:!0,appendControlsTo:"#controlWrap"});f();c("#rotatingGallery").length&&new EasePhotoGallery({galleryContSelector:"#rotatingGallery",dataEl:"#galleryJson",paginate:1E3,isStatic:!0,showTitles:!0,showDescriptions:!0});e();
a();d();b();g()})})(jQuery);
